version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=minecraft-tracecraft
      - DOCKER_INFLUXDB_INIT_BUCKET=minecraft_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Ri0u5ZwseTvdFHWrDKfH5fZVzL04tZkMiVzlIhWm5r3DazI2it2AweHUEZrPjDs1w7UMOfpgOxZRtc__D1gX7w==

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_DATASOURCES_0_NAME: InfluxDB
      GF_DATASOURCES_0_TYPE: influxdb
      GF_DATASOURCES_0_URL: http://influxdb:8086
      GF_DATASOURCES_0_ACCESS: proxy
      GF_DATASOURCES_0_IS_DEFAULT: "true"
      GF_DATASOURCES_0_JSON_DATA: '{"defaultBucket":"minecraft_metrics","organization":"minecraft-tracecraft","version":"Flux","tlsSkipVerify":true}'
      GF_DATASOURCES_0_SECURE_JSON_DATA: '{"token":"Ri0u5Zw…"}'
      GF_INSTALL_PLUGINS: "natel-discrete-panel,grafana-worldmap-panel"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED: true
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
