{
 "title": "Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Packet Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"player_network_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"average_packet_size_bytes\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Server TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Server TPS",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tps\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Packet Per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"player_network_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_per_second\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tick Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket:\"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tick_metrics\" and r._field == \"duration_ms\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> yield(name:\"mean\")"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Player Count",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"player_count\")\n  |> filter(fn: (r) => r._field       == \"count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Player Queued Messages/Queued Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n       r._measurement == \"player_network_stats\" and \n       r._field == \"queued_messages\"\n     )\n  |> aggregateWindow(every: $__interval, fn: sum, createEmpty: false)\n  |> yield(name: \"queued_messages_per_interval\")\n"
    },
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n       r._measurement == \"player_network_stats\" and \n       r._field == \"queued_bytes\"\n     )\n  |> aggregateWindow(every: $__interval, fn: sum, createEmpty: false)\n  |> yield(name: \"queued_bytes_per_interval\")"
    }
   ]
  },
  {
   "title": "Sytem Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_metrics\")\n  |> filter(fn: (r) => \n      r[\"_field\"] == \"max_heap_mb\" or\n      r[\"_field\"] == \"allocated_heap_mb\" or\n      r[\"_field\"] == \"used_heap_mb\" or\n      r[\"_field\"] == \"free_heap_mb\" or\n      r[\"_field\"] == \"thread_count\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Instability Ratio (ISR)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"tick_metrics\" and r._field == \"isr\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> yield()"
    }
   ]
  },
  {
   "title": "Player Chunk Load Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "alias": "Chunk Margin ({{player}})",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"player_chunk_margin\")\n  |> filter(fn: (r) => r._field == \"distance_chunks\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Client Memory ({{player}})",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"client_metrics\")\n  |> filter(fn: (r) => r._field == \"mem\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Client FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    {
     "alias": "Client FPS ({{player}})",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"client_metrics\")\n  |> filter(fn: (r) => r._field == \"fps\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"client_metrics\")\n  |> filter(fn: (r) => r._field == \"ping\")\n  |> group(columns: [\"player\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Block Interactions (Last 100)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "{{_measurement}}",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"block_place\" or r._measurement == \"block_break\")\n  |> filter(fn: (r) => r._field == \"x\" or r._field == \"y\" or r._field == \"z\")\n  |> pivot(rowKey:[\"_time\", \"player\", \"block\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n:100)"
    }
   ]
  },
  {
   "title": "Player Connection Log (Last 100)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "{{_measurement}}",
     "query": "from(bucket: \"minecraft_metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"login\" or r._measurement == \"logout\")\n  |> group(columns: [\"_measurement\", \"player\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n:100)\n  |> keep(columns: [\"_time\", \"_measurement\", \"player\"])"
    }
   ]
  }
 ]
}